# Generated by Django 4.2.13 on 2024-07-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='details',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='email',
            field=models.EmailField(default='@', max_length=80),
        ),
    ]
