# Generated by Django 4.2.13 on 2024-07-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteerprofile_details_volunteerprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='email',
            field=models.EmailField(max_length=80),
        ),
    ]
