# Generated by Django 4.2.13 on 2024-09-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_volunteerprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='email',
        ),
    ]
