# Generated by Django 4.2.13 on 2024-09-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_remove_volunteerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
