# Generated by Django 4.2.13 on 2024-08-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240314_1043'),
        ('checkout', '0009_alter_orderlineitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
